######################################################################
##
## Filename: UARTest1.udo
## Created on: Mon Dec 07 5:44:36 PM Romance Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
